### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by nick-homex** [hashicorp/waypoint-helm#14]
**Is your feature request related to a problem? Please describe.**
A couple of PRs have been merge and I would like to use those features (mainly #9), though no new release has been tagged.

**Describe the solution you'd like**
Tag a new release.

**Describe alternatives you've considered**
Cloning the repo and setting up my own helm repo to get these features.

**Explain any additional use-cases**
Perhaps there should be some automation to automatically tag alpha releases for the helm chart as PRs are merged.

**Additional context**
N/A

**Comment by briancain** [comment]
Hey there @nick-homex - we just released a new version of this chart today! In the future if you'd like some unreleased fixes, you can always clone this repo locally and install waypoint with `helm install <path to local repo>`. Thanks!!
