### ISSUE TITLE
`helm uninstall` appears to not remove the old server context

### ISSUE THREAD

**Issue by krantzinator** [hashicorp/waypoint-helm#19]
**Describe the bug**
`helm uninstall` appears to not remove the old server context, which `waypoint uninstall` does by default, or cleanup other k8s resources that will then block a new install.

**Steps to Reproduce**
* run `helm install waypoint hashicorp/waypoint`
* after everything succeeds and bootstraps, run `helm uninstall waypoint`
* after helm finishes uninstalling and everything is clear, run `helm install waypoint hashicorp/waypoint` again

The k8s cluster will still be using the old server context, and so the runner will not be able to start.

```
$ kubectl logs pod/waypoint-runner-894d94fd4-h4rrt
Error from server (BadRequest): container "waypoint" in pod "waypoint-runner-894d94fd4-h4rrt" is waiting to start: PodInitializing

$ kubectl logs pod/waypoint-server-0
...
2021-11-09T17:36:16.992Z [INFO]  waypoint.server.grpc: /hashicorp.waypoint.Waypoint/BootstrapToken request
2021-11-09T17:36:16.992Z [INFO]  waypoint.server.grpc: /hashicorp.waypoint.Waypoint/BootstrapToken response: error="rpc error: code = PermissionDenied desc = server is already bootstrapped" duration=109.281µs
```

If you delete the context manually, you don't even get that far:
```
$ kubectl logs pod/waypoint-server-0
Error from server: Get "https://[IP]:[port]/containerLogs/default/waypoint-server-0/waypoint": EOF
```

**Expected behavior**
I would expect `helm uninstall` to mirror `waypoint uninstall` as usefully as possible.

Alternatively, our documentation can include the specific instructions in our Upgrade and Uninstall guides that are unique to helm.

**Waypoint Platform Versions**
`waypoint version: full_string="v0.6.2 (99350730+CHANGES)" version=v0.6.2`

* Helm CLI Version: `version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.17"}`
* Kubernetes Version:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.10-gke.1600", GitCommit:"ef8e9f64449d73f9824ff5838cea80e21ec6c127", GitTreeState:"clean", BuildDate:"2021-09-06T09:24:20Z", GoVersion:"go1.15.15b5", Compiler:"gc", Platform:"linux/amd64"}
```
* Waypoint CLI Version: 0.6.2
* Waypoint Server Platform and Version: kubernetes, 0.6.2

**Comment by mitchellh** [comment]
This won't be possible, since Helm can't do anything on your local machine. Similarly, we don't setup the local context on `helm install` either. You have to manually run the `waypoint login` command to do that. We could potentially introduce a `waypoint logout` command though instead?
